---
driver:
  name: docker
  use_sudo: false

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04
  - name: ubuntu-16.04
  - name: centos-7.2

suites:
  - name: default
    run_list:
      - recipe[chef-inspec::default]
    attributes:
      inspec:
        fail_on_error: false
        profiles: 
          - https://github.com/dev-sec/linux-baseline
          #- https://github.com/dev-sec/cis-docker-benchmark